#source 'https://github.com/CocoaPods/Specs.git

use_frameworks!
platform :ios, '12.0'

target 'EdimobIOSAdsSDK_Example' do
  pod 'EdimobIOSAdsSDK', :path => '../', :subspecs => ['Core','CocoaHTTPServer','SDWebImage','Masonry','KSCrash','WechatOpenSDK']
  
  pod 'Ads-CN-Beta', '~> 7.2.0.0', :subspecs => ['BUAdSDK', 'CSJMediation']
#  pod 'HRAdSDK/HR','1.7.19.0'
  pod 'WechatOpenSDK'
#  #pod 'KSCrash', '~> 1.17.7'
  pod 'GDTMobSDK', '~> 4.15.60'
  pod 'KSAdSDK', '~> 4.9.20'
  pod 'QMAdSDK', '~> 1.3.7'
#  pod 'AnyThinkiOS','6.4.92'
  pod 'JADYun', '2.6.8'
  pod 'BeiZiSDK-iOS/BeiZiSDK-iOS', '4.90.7.0'
#  pod 'UBiXMediationSDK', '2.10.1'
#  pod 'UBiXMUBiXAdapter'
  pod 'MSMobAdSDK/MS','2.7.7.2'
  pod 'OctopusSDK', '2.5.10.15'
#  pod 'SDWebImage'  '~> 5.21.2'
#  pod 'CocoaHTTPServer'
#pod 'Toast-Swift', '~> 5.0'
  target 'EdimobIOSAdsSDK_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['CocoaHTTPServer','CocoaLumberjack','CocoaAsyncSocket','Masonry', 'MBProgressHUD'].include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
