use_frameworks!

platform :ios, '12.0'

target 'EdimobIOSAdsSDK_Example' do
  pod 'EdimobIOSAdsSDK', :path => '../', :subspecs => ['Core','CocoaHTTPServer','SDWebImage','Masonry','KSCrash','WechatOpenSDK']
  
#  pod 'Ads-CN-Beta', '~> 6.8.0.6', :subspecs => ['BUAdSDK', 'CSJMediation']
  pod 'HRAdSDK/HR','1.7.19.0'
#  pod 'WechatOpenSDK'
#  pod 'KSCrash', '~> 1.17.7'
#  pod 'GDTMobSDK', '~> 4.15.41'
#  pod 'KSAdSDK', '~> 3.3.76'
  pod 'QMAdSDK', '~> 1.3.4'
  pod 'AnyThinkiOS','6.4.76'
  pod 'JADYun', '2.6.8'
  pod 'UBiXMediationSDK', '2.9.0'
  pod 'UBiXMUBiXAdapter'
  pod 'TradPlusAdSDK', '14.0.0'
  pod 'TradPlusAdSDK/FacebookAdapter', '14.0.0'
  pod 'FBAudienceNetwork','6.20.0'
  pod 'TradPlusAdSDK/UnityAdapter', '14.0.0'
  pod 'UnityAds','4.15.0'
  pod 'TradPlusAdSDK/AppLovinAdapter','14.0.0'
  pod 'AppLovinSDK','13.3.0'
  pod 'TradPlusAdSDK/VungleAdapter', '14.0.0'
  pod 'VungleAds', '7.5.1'
  pod 'TradPlusAdSDK/AdColonyAdapter','14.0.0'
  pod 'AdColony','4.9.0'
  pod 'TradPlusAdSDK/InMobiAdapter', '14.0.0'
  pod 'InMobiSDK' ,'10.8.3'
  pod 'TradPlusAdSDK/MintegralAdapter', '14.0.0'
  pod 'MintegralAdSDK' ,'7.7.8'
  pod 'MintegralAdSDK/All','7.7.8'
  pod 'TradPlusAdSDK/KuaiShouAdapter', '14.0.0'
  pod 'KSAdSDK', '4.4.20.1'
  pod 'TradPlusAdSDK/GDTMobAdapter', '14.0.0'
  pod 'GDTMobSDK', '4.15.40'
  pod 'TradPlusAdSDK/PangleAdapter', '14.0.0'
  pod 'Ads-Global', '7.2.0.4'
  pod 'TradPlusAdSDK/TPCrossAdapter', '14.0.0'
  pod 'TradPlusAdSDK/CSJAdapter','14.0.0';
  pod 'Ads-CN/BUAdSDK', '6.8.2.1'
#  pod 'CocoaHTTPServer'
  target 'EdimobIOSAdsSDK_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['CocoaHTTPServer','CocoaLumberjack','CocoaAsyncSocket','Masonry', 'MBProgressHUD'].include?(target.name)
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
